Repository chiayunrong/Focat, pull requests merged in 2022-05, with the labels that each got.

#24 [Screen] Getting started
  .prettierrc
  navigation/StackNavigator.js
  package-lock.json
  package.json
  screens/Login/getting_started.js
  screens/Settings/settings.js
  utils/checkFirstLaunch.js
Labels: feature

#27 [Screen] Signup
  App.js
  components/email_textinput.js
  components/password_textinput.js
  firebase/index.js
  navigation/StackNavigator.js
  package-lock.json
  package.json
  screens/Login/login.js
  screens/Settings/settings.js
  screens/Signup/signup.js
Labels: feature

#26 [Screen] Settings
  components/login_logout_button.js
  navigation/DrawerContent.js
  navigation/DrawerNavigator.js
  screens/Profile/profile.js
  screens/Settings/account_modal.js
  screens/Settings/reminders_modal.js
  screens/Settings/settings.js
  screens/Settings/themes_modal.js
Labels: feature

#25 Countdown timer / stopwatch
  components/clock.js
  components/start_stop_button.js
  package-lock.json
  package.json
  screens/Home/home.js
  screens/Home/stopwatch.js
  screens/Home/timer.js
Labels: feature

#30 Add back button on signup screen
  navigation/StackNavigator.js
Labels: enhancement

#32 Update README for Milestone 1
  README.md
Labels: documentation
